const Message = require("../models/message.model");
const Conversation = require("../models/conversation.model");
const { getIO } = require("../realtime/socket");
const { buildPreview } = require("../utils/previewBuilder");
const logger = require("../utils/logger");

// MongoDB duplicate key error code
const DUPLICATE_KEY_ERROR_CODE = 11000;

// Fixed sender identity for all system-generated messages
const SYSTEM_SENDER_ID = "SYSTEM_USER";

// Valid system event codes — must mirror the systemEvent enum in message.model.js
const SYSTEM_EVENTS = [
    "SESSION_STARTED",
    "CONSULTATION_COMPLETED",
    "CHAT_CLOSED",
    "CONSULTATION_CANCELLED",
    "PATIENT_NO_SHOW",
    "DOCTOR_NO_SHOW"
];

/**
 * Inserts a system divider message into the conversation timeline.
 *
 * System messages are automatically generated by the backend on session
 * lifecycle events. They bypass all user-level permission checks, participant
 * validation, and patient message limits.
 *
 * Idempotency is enforced via a deterministic clientMessageId:
 *   `${systemEvent}-${consultationId}`
 *
 * If a duplicate key error is encountered (i.e., this event was already
 * recorded for this consultation), the existing document is fetched and
 * returned unchanged.
 *
 * @param {Object} input
 * @param {string} input.consultationId       - External consultation ID
 * @param {string} input.conversationId       - MongoDB ObjectId ref to Conversation
 * @param {string} input.consultationSessionId - MongoDB ObjectId ref to ConsultationChatSession
 * @param {string} input.systemEvent          - One of SYSTEM_EVENTS enum values
 * @returns {Promise<Object>} Saved message document (plain object)
 */
const insertSystemMessage = async ({
    consultationId,
    conversationId,
    consultationSessionId,
    systemEvent
}) => {
    // ── 0. Input validation ───────────────────────────────────────────────
    if (!consultationId) {
        throw new Error("insertSystemMessage: consultationId is required");
    }
    if (!conversationId) {
        throw new Error("insertSystemMessage: conversationId is required");
    }
    if (!consultationSessionId) {
        throw new Error("insertSystemMessage: consultationSessionId is required");
    }
    if (!SYSTEM_EVENTS.includes(systemEvent)) {
        throw new Error(
            `insertSystemMessage: invalid systemEvent "${systemEvent}". ` +
            `Must be one of: ${SYSTEM_EVENTS.join(", ")}`
        );
    }

    // ── 1. Deterministic idempotency key ──────────────────────────────────
    const clientMessageId = `${systemEvent}-${consultationId}`;

    // ── 2. Early duplicate check ──────────────────────────────────────────
    // Avoids hitting the unique index on clientMessageId in the common path.
    const existing = await Message.findOne({
        conversationId,
        clientMessageId
    }).lean();

    if (existing) {
        logger.info("System message already exists — skipping insertion", {
            systemEvent,
            consultationId,
            clientMessageId,
            existingMessageId: existing._id
        });
        return existing;
    }

    // ── 3. Persist system message ─────────────────────────────────────────
    let message;

    try {
        message = await Message.create({
            conversationId,
            consultationId,
            consultationSessionId,
            senderId: SYSTEM_SENDER_ID,
            senderRole: "SYSTEM",
            type: "SYSTEM",
            systemEvent,
            // content is intentionally omitted — frontend renders localised
            // text from systemEvent; no free-text is stored.
            status: "SENT",
            clientMessageId
        });
    } catch (error) {
        // Race condition: another request beat us between the early check and
        // the insert. Fetch and return the existing document instead.
        if (error.code === DUPLICATE_KEY_ERROR_CODE) {
            logger.warn(
                "Concurrent system message insert detected — fetching existing",
                { systemEvent, consultationId, clientMessageId }
            );

            const raceExisting = await Message.findOne({
                conversationId,
                clientMessageId
            }).lean();

            if (raceExisting) {
                return raceExisting;
            }
        }

        throw error;
    }

    // ── 4. Update Conversation lastMessage pointer + preview fields ────────
    const messageTimestamp = message.createdAt || new Date();
    const preview = buildPreview({
        type:        "SYSTEM",
        senderRole:  "SYSTEM",
        systemEvent
    });

    await Conversation.findByIdAndUpdate(conversationId, {
        $set: {
            lastMessage:        message._id,
            lastMessageAt:      messageTimestamp,
            lastMessagePreview: preview.lastMessagePreview,
            lastMessageType:    preview.lastMessageType,
            lastSenderRole:     preview.lastSenderRole,
            lastSystemEvent:    preview.lastSystemEvent
        }
    });

    // NOTE: insertSystemMessage does NOT call publishUnreadIncrement.
    // System divider messages are excluded from unread counts per spec.

    logger.info("System message inserted", {
        messageId: message._id,
        systemEvent,
        consultationId,
        conversationId,
        clientMessageId
    });

    const messageObject = message.toObject();

    // Non-blocking socket fan-out — failure must never affect session lifecycle
    try {
        getIO().to(conversationId.toString()).emit("new_message", messageObject);
    } catch (err) {
        logger.warn("Socket fan-out failed for system message", {
            systemEvent,
            conversationId,
            error: err.message
        });
    }

    return messageObject;
};

module.exports = {
    insertSystemMessage
};
